"""nullable columns

Revision ID: 4b50f5396ee1
Revises: 4801596247a5
Create Date: 2024-07-20 12:31:55.304476

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4b50f5396ee1"
down_revision: Union[str, None] = "4801596247a5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("file_metadata", "file_type", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("file_metadata", "architecture", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("file_metadata", "num_imports", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("file_metadata", "num_exports", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("file_metadata", "num_exports", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("file_metadata", "num_imports", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("file_metadata", "architecture", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("file_metadata", "file_type", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
