"""index on path

Revision ID: a17cab59bdaa
Revises: 4b50f5396ee1
Create Date: 2024-07-27 19:52:52.207756

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "a17cab59bdaa"
down_revision: Union[str, None] = "4b50f5396ee1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("file_metadata_path_key", "file_metadata", type_="unique")
    op.create_index(op.f("ix_file_metadata_path"), "file_metadata", ["path"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_file_metadata_path"), table_name="file_metadata")
    op.create_unique_constraint("file_metadata_path_key", "file_metadata", ["path"])
    # ### end Alembic commands ###
