name: Run Docker Compose

on:
  push:
    branches:
      - main

jobs:
  run-docker-compose:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Get number of CPU cores
        run: |
          echo "cores=$(nproc)" >> $GITHUB_ENV

      - name: Build and start Docker Compose in the background
        env:
          SPARK_WORKER_CORES: ${{ env.cores }}
        run: |
          sed -i "s/16/${SPARK_WORKER_CORES}/" docker-compose.yml
          docker-compose up --build -d

      - name: Stream logs of app service
        run: |
          docker-compose logs -f app &

      - name: Wait for app to finish
        run: |
          while docker-compose ps | grep app | grep -q "Up"; do
            sleep 10
          done

      - name: Bring down Docker Compose
        run: docker-compose down
